name: Run Glue Crawler

on:
  workflow_dispatch:        # manual trigger
  push:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: pip install awscli

      - name: Start Glue Crawler
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Starting Glue Crawler: spend_data_crawler"
          aws glue start-crawler --name spend_data_crawler --region $AWS_REGION
