name: Run Glue Transformations

on:
  workflow_dispatch:
  push:
    paths:
      - 'glue_jobs/**'

jobs:
  run-glue-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install AWS CLI and boto3
        run: |
          pip install awscli boto3

      - name: Run Glue ETL Job
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws glue start-job-run --job-name CalendlyDailyEventJob
